// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, UsersCheckAvailabilityData, UsersCheckAvailabilityResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse, LeaguesReadLeaguesData, LeaguesReadLeaguesResponse, LeaguesCreateLeagueData, LeaguesCreateLeagueResponse, LeaguesReadLeagueByIdData, LeaguesReadLeagueByIdResponse, LeaguesUpdateLeagueData, LeaguesUpdateLeagueResponse, LeaguesDeleteLeagueData, LeaguesDeleteLeagueResponse, SeasonsReadSeasonsData, SeasonsReadSeasonsResponse, SeasonsCreateSeasonData, SeasonsCreateSeasonResponse, SeasonsGetSeasonData, SeasonsGetSeasonResponse, SeasonsUpdateSeasonData, SeasonsUpdateSeasonResponse, SeasonsEndSeasonData, SeasonsEndSeasonResponse, SeasonsDeleteSeasonData, SeasonsDeleteSeasonResponse, ClubsReadClubsData, ClubsReadClubsResponse, ClubsCreateClubData, ClubsCreateClubResponse, ClubsUpdateClubData, ClubsUpdateClubResponse, ClubsDeleteClubData, ClubsDeleteClubResponse } from './types.gen';

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Check Availability
     * Check if an email or gamertag is available.
     * This endpoint is used for real-time validation during registration.
     * Returns {"available": true/false}
     * @param data The data for the request.
     * @param data.email
     * @param data.gamertag
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static checkAvailability(data: UsersCheckAvailabilityData = {}): CancelablePromise<UsersCheckAvailabilityResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/check-availability',
            query: {
                email: data.email,
                gamertag: data.gamertag
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}

export class LeaguesService {
    /**
     * Read Leagues
     * Retrieve leagues.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns LeaguesPublic Successful Response
     * @throws ApiError
     */
    public static readLeagues(data: LeaguesReadLeaguesData = {}): CancelablePromise<LeaguesReadLeaguesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/leagues/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Create League
     * Create a new league.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns LeaguePublic Successful Response
     * @throws ApiError
     */
    public static createLeague(data: LeaguesCreateLeagueData): CancelablePromise<LeaguesCreateLeagueResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/leagues/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read League By Id
     * Get a specific league by id.
     * @param data The data for the request.
     * @param data.leagueId
     * @returns LeaguePublic Successful Response
     * @throws ApiError
     */
    public static readLeagueById(data: LeaguesReadLeagueByIdData): CancelablePromise<LeaguesReadLeagueByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/leagues/{league_id}',
            path: {
                league_id: data.leagueId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Update League
     * Update a league.
     * @param data The data for the request.
     * @param data.leagueId
     * @param data.requestBody
     * @returns LeaguePublic Successful Response
     * @throws ApiError
     */
    public static updateLeague(data: LeaguesUpdateLeagueData): CancelablePromise<LeaguesUpdateLeagueResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/leagues/{league_id}',
            path: {
                league_id: data.leagueId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Delete League
     * Delete a league.
     * @param data The data for the request.
     * @param data.leagueId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteLeague(data: LeaguesDeleteLeagueData): CancelablePromise<LeaguesDeleteLeagueResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/leagues/{league_id}',
            path: {
                league_id: data.leagueId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class SeasonsService {
    /**
     * Read Seasons
     * List all seasons for a league.
     */
    public static readSeasons(data: SeasonsReadSeasonsData): CancelablePromise<SeasonsReadSeasonsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/leagues/{league_id}/seasons/',
            path: {
                league_id: data.leagueId
            },
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Create Season
     * Create a new season. start_date is set automatically server-side.
     */
    public static createSeason(data: SeasonsCreateSeasonData): CancelablePromise<SeasonsCreateSeasonResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/leagues/{league_id}/seasons/',
            path: {
                league_id: data.leagueId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Get Season
     * Get a specific season by id.
     */
    public static getSeason(data: SeasonsGetSeasonData): CancelablePromise<SeasonsGetSeasonResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/leagues/{league_id}/seasons/{season_id}',
            path: {
                league_id: data.leagueId,
                season_id: data.seasonId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Update Season
     * Update a season name.
     */
    public static updateSeason(data: SeasonsUpdateSeasonData): CancelablePromise<SeasonsUpdateSeasonResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/leagues/{league_id}/seasons/{season_id}',
            path: {
                league_id: data.leagueId,
                season_id: data.seasonId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * End Season
     * End a season — sets end_date to current UTC time.
     */
    public static endSeason(data: SeasonsEndSeasonData): CancelablePromise<SeasonsEndSeasonResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/leagues/{league_id}/seasons/{season_id}/end',
            path: {
                league_id: data.leagueId,
                season_id: data.seasonId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Delete Season
     * Delete a season.
     */
    public static deleteSeason(data: SeasonsDeleteSeasonData): CancelablePromise<SeasonsDeleteSeasonResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/leagues/{league_id}/seasons/{season_id}',
            path: {
                league_id: data.leagueId,
                season_id: data.seasonId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ClubsService {
    /**
     * Read Clubs
     * List all clubs in a season.
     */
    public static readClubs(data: ClubsReadClubsData): CancelablePromise<ClubsReadClubsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/leagues/{league_id}/seasons/{season_id}/clubs/',
            path: {
                league_id: data.leagueId,
                season_id: data.seasonId
            },
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Create Club
     * Create a new club and add it to the season.
     */
    public static createClub(data: ClubsCreateClubData): CancelablePromise<ClubsCreateClubResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/leagues/{league_id}/seasons/{season_id}/clubs/',
            path: {
                league_id: data.leagueId,
                season_id: data.seasonId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Update Club
     * Update a club's name, EA ID, or logo URL.
     */
    public static updateClub(data: ClubsUpdateClubData): CancelablePromise<ClubsUpdateClubResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/leagues/{league_id}/seasons/{season_id}/clubs/{club_id}',
            path: {
                league_id: data.leagueId,
                season_id: data.seasonId,
                club_id: data.clubId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Delete Club
     * Remove a club from this season.
     */
    public static deleteClub(data: ClubsDeleteClubData): CancelablePromise<ClubsDeleteClubResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/leagues/{league_id}/seasons/{season_id}/clubs/{club_id}',
            path: {
                league_id: data.leagueId,
                season_id: data.seasonId,
                club_id: data.clubId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}