// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    gamertag: string;
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    gamertag: string;
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
    gamertag: string;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    gamertag?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    gamertag?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersCheckAvailabilityData = {
    email?: (string | null);
    gamertag?: (string | null);
};

export type UsersCheckAvailabilityResponse = ({
    [key: string]: (boolean);
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

// League types
export type LeagueType = '3v3' | '6v6';

export type LeagueCreate = {
    name: string;
    league_type: LeagueType;
    is_active?: boolean;
    description?: (string | null);
};

export type LeaguePublic = {
    name: string;
    league_type: LeagueType;
    is_active?: boolean;
    description?: (string | null);
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type LeaguesPublic = {
    data: Array<LeaguePublic>;
    count: number;
};

export type LeagueUpdate = {
    name?: (string | null);
    league_type?: (LeagueType | null);
    is_active?: (boolean | null);
    description?: (string | null);
};

// League request/response types
export type LeaguesReadLeaguesData = {
    skip?: number;
    limit?: number;
};

export type LeaguesReadLeaguesResponse = (LeaguesPublic);

export type LeaguesCreateLeagueData = {
    requestBody: LeagueCreate;
};

export type LeaguesCreateLeagueResponse = (LeaguePublic);

export type LeaguesReadLeagueByIdData = {
    leagueId: string;
};

export type LeaguesReadLeagueByIdResponse = (LeaguePublic);

export type LeaguesUpdateLeagueData = {
    leagueId: string;
    requestBody: LeagueUpdate;
};

export type LeaguesUpdateLeagueResponse = (LeaguePublic);

export type LeaguesDeleteLeagueData = {
    leagueId: string;
};

export type LeaguesDeleteLeagueResponse = (Message);

// Season types
export type SeasonCreate = {
    name: string;
    league_id: string;
};

export type SeasonPublic = {
    name: string;
    league_id: string;
    id: string;
    start_date: string;
    end_date?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type SeasonsPublic = {
    data: Array<SeasonPublic>;
    count: number;
};

export type SeasonUpdate = {
    name?: (string | null);
};

// Season request/response types
export type SeasonsReadSeasonsData = {
    leagueId: string;
    skip?: number;
    limit?: number;
};

export type SeasonsReadSeasonsResponse = SeasonsPublic;

export type SeasonsCreateSeasonData = {
    leagueId: string;
    requestBody: SeasonCreate;
};

export type SeasonsCreateSeasonResponse = SeasonPublic;

export type SeasonsGetSeasonData = {
    leagueId: string;
    seasonId: string;
};

export type SeasonsGetSeasonResponse = SeasonPublic;

export type SeasonsUpdateSeasonData = {
    leagueId: string;
    seasonId: string;
    requestBody: SeasonUpdate;
};

export type SeasonsUpdateSeasonResponse = SeasonPublic;

export type SeasonsEndSeasonData = {
    leagueId: string;
    seasonId: string;
};

export type SeasonsEndSeasonResponse = SeasonPublic;

export type SeasonsDeleteSeasonData = {
    leagueId: string;
    seasonId: string;
};

export type SeasonsDeleteSeasonResponse = Message;

// Club types
export type ClubSeasonHistory = {
    season_id: string;
    season_name: string;
    league_id: string;
    league_name: string;
    is_active: boolean;
    start_date?: (string | null);
    end_date?: (string | null);
};

export type ClubCreate = {
    name: string;
    ea_id?: (string | null);
    logo_url?: (string | null);
};

export type ClubPublic = {
    name: string;
    ea_id?: (string | null);
    logo_url?: (string | null);
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
    season_count: number;
    history?: Array<ClubSeasonHistory>;
};

export type ClubsPublic = {
    data: Array<ClubPublic>;
    count: number;
};

export type ClubUpdate = {
    name?: (string | null);
    ea_id?: (string | null);
    logo_url?: (string | null);
};

// Club request/response types (season-scoped)
export type ClubsReadClubsData = {
    leagueId: string;
    seasonId: string;
    skip?: number;
    limit?: number;
};

export type ClubsReadClubsResponse = ClubsPublic;

export type ClubsCreateClubData = {
    leagueId: string;
    seasonId: string;
    requestBody: ClubCreate;
};

export type ClubsCreateClubResponse = ClubPublic;

export type ClubsAssignClubData = {
    leagueId: string;
    seasonId: string;
    clubId: string;
};

export type ClubsAssignClubResponse = ClubPublic;

export type ClubsUpdateClubData = {
    leagueId: string;
    seasonId: string;
    clubId: string;
    requestBody: ClubUpdate;
};

export type ClubsUpdateClubResponse = ClubPublic;

export type ClubsDeleteClubData = {
    leagueId: string;
    seasonId: string;
    clubId: string;
};

export type ClubsDeleteClubResponse = Message;

// Scheduler types
export type SchedulerConfigCreate = {
    days_of_week?: Array<number>;
    start_hour?: number;
    end_hour?: number;
    interval_minutes?: number;
    interval_seconds?: number;
};

export type SchedulerConfigUpdate = {
    days_of_week?: (Array<number> | null);
    start_hour?: (number | null);
    end_hour?: (number | null);
    interval_minutes?: (number | null);
    interval_seconds?: (number | null);
};

export type SchedulerConfigPublic = {
    id: string;
    season_id: string;
    is_active: boolean;
    is_paused: boolean;
    days_of_week: Array<number>;
    start_hour: number;
    end_hour: number;
    interval_minutes: number;
    interval_seconds: number;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type SchedulerConfigWithStatus = SchedulerConfigPublic & {
    season_name?: (string | null);
    league_name?: (string | null);
    last_run_at?: (string | null);
    last_run_status?: (string | null);
    total_matches: number;
    is_running: boolean;
};

export type SchedulerRunStatus = 'running' | 'success' | 'failed';

export type SchedulerRunPublic = {
    id: string;
    scheduler_config_id: string;
    season_id: string;
    started_at: string;
    finished_at?: (string | null);
    status: SchedulerRunStatus;
    matches_fetched: number;
    matches_new: number;
    error_message?: (string | null);
};

export type SchedulerRunsPublic = {
    data: Array<SchedulerRunPublic>;
    count: number;
};

// Scheduler request/response types
export type SchedulersListAllSchedulersResponse = Array<SchedulerConfigWithStatus>;

export type SchedulersGetSchedulerData = {
    seasonId: string;
};

export type SchedulersGetSchedulerResponse = SchedulerConfigWithStatus;

export type SchedulersCreateSchedulerData = {
    seasonId: string;
    requestBody: SchedulerConfigCreate;
};

export type SchedulersCreateSchedulerResponse = SchedulerConfigPublic;

export type SchedulersUpdateSchedulerData = {
    seasonId: string;
    requestBody: SchedulerConfigUpdate;
};

export type SchedulersUpdateSchedulerResponse = SchedulerConfigPublic;

export type SchedulersDeleteSchedulerData = {
    seasonId: string;
};

export type SchedulersDeleteSchedulerResponse = Message;

export type SchedulersStartSchedulerData = {
    seasonId: string;
};

export type SchedulersStartSchedulerResponse = SchedulerConfigPublic;

export type SchedulersStopSchedulerData = {
    seasonId: string;
};

export type SchedulersStopSchedulerResponse = SchedulerConfigPublic;

export type SchedulersPauseSchedulerData = {
    seasonId: string;
};

export type SchedulersPauseSchedulerResponse = SchedulerConfigPublic;

export type SchedulersResumeSchedulerData = {
    seasonId: string;
};

export type SchedulersResumeSchedulerResponse = SchedulerConfigPublic;

export type SchedulersGetSchedulerRunsData = {
    seasonId: string;
    skip?: number;
    limit?: number;
};

export type SchedulersGetSchedulerRunsResponse = SchedulerRunsPublic;

// Match types
export type MatchPublic = {
    id: string;
    ea_match_id: string;
    ea_timestamp: number;
    season_id: string;
    club_id: string;
    home_club_ea_id?: (string | null);
    away_club_ea_id?: (string | null);
    home_score?: (number | null);
    away_score?: (number | null);
    created_at?: (string | null);
};

export type MatchWithContext = MatchPublic & {
    season_name?: (string | null);
    league_name?: (string | null);
    is_home?: (boolean | null);
    opponent_ea_id?: (string | null);
};

export type MatchesPublic = {
    data: Array<MatchWithContext>;
    count: number;
};

// Match request/response types
export type MatchesGetAllMatchesData = {
    skip?: number;
    limit?: number;
    seasonId?: string;
    clubId?: string;
    leagueId?: string;
};

export type MatchesGetAllMatchesResponse = MatchesPublic;

export type MatchesGetClubMatchesData = {
    clubId: string;
    skip?: number;
    limit?: number;
};

export type MatchesGetClubMatchesResponse = MatchesPublic;

export type MatchesGetSeasonMatchesData = {
    seasonId: string;
    skip?: number;
    limit?: number;
};

export type MatchesGetSeasonMatchesResponse = MatchesPublic;
// Global clubs request/response types
export type GlobalClubsReadAllData = {
    skip?: number;
    limit?: number;
};

export type GlobalClubsReadAllResponse = ClubsPublic;

export type GlobalClubsCreateData = {
    requestBody: ClubCreate;
};

export type GlobalClubsCreateResponse = ClubPublic;

export type GlobalClubsReadOneData = {
    clubId: string;
};

export type GlobalClubsReadOneResponse = ClubPublic;

export type GlobalClubsUpdateData = {
    clubId: string;
    requestBody: ClubUpdate;
};

export type GlobalClubsUpdateResponse = ClubPublic;

export type GlobalClubsDeleteData = {
    clubId: string;
};

export type GlobalClubsDeleteResponse = Message;

export type GlobalClubsAssignData = {
    clubId: string;
    seasonId: string;
};

export type GlobalClubsAssignResponse = ClubPublic;

// Player types
export type PlayerPublic = {
    id: string;
    ea_player_id: string;
    gamertag: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type PlayersPublic = {
    data: Array<PlayerPublic>;
    count: number;
};

export type PlayerMatchStatsPublic = {
    id: string;
    ea_player_id: string;
    ea_match_id: string;
    ea_timestamp?: (number | null);
    match_id?: (string | null);
    stat_class?: (number | null);
    glbrksavepct?: (number | null);
    glbrksaves?: (number | null);
    glbrkshots?: (number | null);
    gldsaves?: (number | null);
    glga?: (number | null);
    glgaa?: (number | null);
    glpensavepct?: (number | null);
    glpensaves?: (number | null);
    glpenshots?: (number | null);
    glpkclearzone?: (number | null);
    glpokechecks?: (number | null);
    glsavepct?: (number | null);
    glsaves?: (number | null);
    glshots?: (number | null);
    glsoperiods?: (number | null);
    is_guest?: (number | null);
    opponent_club_id?: (string | null);
    opponent_score?: (number | null);
    opponent_team_id?: (string | null);
    player_dnf?: (number | null);
    player_level?: (number | null);
    p_nhl_online_game_type?: (string | null);
    position?: (string | null);
    pos_sorted?: (number | null);
    rating_defense?: (number | null);
    rating_offense?: (number | null);
    rating_teamplay?: (number | null);
    score?: (number | null);
    skassists?: (number | null);
    skbs?: (number | null);
    skdeflections?: (number | null);
    skfol?: (number | null);
    skfopct?: (number | null);
    skfow?: (number | null);
    skgiveaways?: (number | null);
    skgoals?: (number | null);
    skgwg?: (number | null);
    skhits?: (number | null);
    skinterceptions?: (number | null);
    skpassattempts?: (number | null);
    skpasses?: (number | null);
    skpasspct?: (number | null);
    skpenaltiesdrawn?: (number | null);
    skpim?: (number | null);
    skpkclearzone?: (number | null);
    skplusmin?: (number | null);
    skpossession?: (number | null);
    skppg?: (number | null);
    sksaucerpasses?: (number | null);
    skshg?: (number | null);
    skshotattempts?: (number | null);
    skshotonnetpct?: (number | null);
    skshotpct?: (number | null);
    skshots?: (number | null);
    sktakeaways?: (number | null);
    team_id?: (string | null);
    team_side?: (number | null);
    toi?: (number | null);
    toiseconds?: (number | null);
    client_platform?: (string | null);
    created_at?: (string | null);
};

export type PlayerDetailPublic = {
    id: string;
    ea_player_id: string;
    gamertag: string;
    created_at?: (string | null);
    updated_at?: (string | null);
    stats: Array<PlayerMatchStatsPublic>;
};

export type PlayersListPlayersData = {
    skip?: number;
    limit?: number;
    search?: (string | null);
};

export type PlayersListPlayersResponse = PlayersPublic;

export type PlayersGetPlayerData = {
    eaPlayerId: string;
};

export type PlayersGetPlayerResponse = PlayerDetailPublic;
