"""add gamertag

Revision ID: 024bf9e73ed7
Revises: 2adebecf44e7
Create Date: 2026-02-17 10:41:16.245911

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '024bf9e73ed7'
down_revision = '2adebecf44e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gamertag', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.create_index(op.f('ix_user_gamertag'), 'user', ['gamertag'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_gamertag'), table_name='user')
    op.drop_column('user', 'gamertag')
    # ### end Alembic commands ###
