"""add unique constraint to club name

Revision ID: 526f79a65431
Revises: c0757c482369
Create Date: 2026-02-21 11:35:34.098466

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '526f79a65431'
down_revision = 'c0757c482369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_club_name'), 'club', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_club_name'), table_name='club')
    # ### end Alembic commands ###
