"""add_club_and_club_season_tables

Revision ID: c0757c482369
Revises: 6bb3d1a4552f
Create Date: 2026-02-21 10:16:10.909803

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c0757c482369'
down_revision = '6bb3d1a4552f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ea_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club_season',
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('club_id', 'season_id')
    )
    op.drop_constraint(op.f('season_league_id_fkey'), 'season', type_='foreignkey')
    op.create_foreign_key(None, 'season', 'league', ['league_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'season', type_='foreignkey')
    op.create_foreign_key(op.f('season_league_id_fkey'), 'season', 'league', ['league_id'], ['id'])
    op.drop_table('club_season')
    op.drop_table('club')
    # ### end Alembic commands ###
