/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutLeaguesRouteImport } from './routes/_layout/leagues'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutLeaguesLeagueIdRouteImport } from './routes/_layout/leagues.$leagueId'
import { Route as LayoutLeaguesLeagueIdSeasonsSeasonIdRouteImport } from './routes/_layout/leagues.$leagueId.seasons.$seasonId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLeaguesRoute = LayoutLeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLeaguesLeagueIdRoute = LayoutLeaguesLeagueIdRouteImport.update({
  id: '/$leagueId',
  path: '/$leagueId',
  getParentRoute: () => LayoutLeaguesRoute,
} as any)
const LayoutLeaguesLeagueIdSeasonsSeasonIdRoute =
  LayoutLeaguesLeagueIdSeasonsSeasonIdRouteImport.update({
    id: '/seasons/$seasonId',
    path: '/seasons/$seasonId',
    getParentRoute: () => LayoutLeaguesLeagueIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/leagues': typeof LayoutLeaguesRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/leagues/$leagueId': typeof LayoutLeaguesLeagueIdRouteWithChildren
  '/leagues/$leagueId/seasons/$seasonId': typeof LayoutLeaguesLeagueIdSeasonsSeasonIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/leagues': typeof LayoutLeaguesRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/leagues/$leagueId': typeof LayoutLeaguesLeagueIdRouteWithChildren
  '/leagues/$leagueId/seasons/$seasonId': typeof LayoutLeaguesLeagueIdSeasonsSeasonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/leagues': typeof LayoutLeaguesRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/leagues/$leagueId': typeof LayoutLeaguesLeagueIdRouteWithChildren
  '/_layout/leagues/$leagueId/seasons/$seasonId': typeof LayoutLeaguesLeagueIdSeasonsSeasonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/leagues'
    | '/settings'
    | '/leagues/$leagueId'
    | '/leagues/$leagueId/seasons/$seasonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/leagues'
    | '/settings'
    | '/'
    | '/leagues/$leagueId'
    | '/leagues/$leagueId/seasons/$seasonId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/leagues'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/leagues/$leagueId'
    | '/_layout/leagues/$leagueId/seasons/$seasonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/leagues': {
      id: '/_layout/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LayoutLeaguesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/leagues/$leagueId': {
      id: '/_layout/leagues/$leagueId'
      path: '/$leagueId'
      fullPath: '/leagues/$leagueId'
      preLoaderRoute: typeof LayoutLeaguesLeagueIdRouteImport
      parentRoute: typeof LayoutLeaguesRoute
    }
    '/_layout/leagues/$leagueId/seasons/$seasonId': {
      id: '/_layout/leagues/$leagueId/seasons/$seasonId'
      path: '/seasons/$seasonId'
      fullPath: '/leagues/$leagueId/seasons/$seasonId'
      preLoaderRoute: typeof LayoutLeaguesLeagueIdSeasonsSeasonIdRouteImport
      parentRoute: typeof LayoutLeaguesLeagueIdRoute
    }
  }
}

interface LayoutLeaguesLeagueIdRouteChildren {
  LayoutLeaguesLeagueIdSeasonsSeasonIdRoute: typeof LayoutLeaguesLeagueIdSeasonsSeasonIdRoute
}

const LayoutLeaguesLeagueIdRouteChildren: LayoutLeaguesLeagueIdRouteChildren = {
  LayoutLeaguesLeagueIdSeasonsSeasonIdRoute:
    LayoutLeaguesLeagueIdSeasonsSeasonIdRoute,
}

const LayoutLeaguesLeagueIdRouteWithChildren =
  LayoutLeaguesLeagueIdRoute._addFileChildren(
    LayoutLeaguesLeagueIdRouteChildren,
  )

interface LayoutLeaguesRouteChildren {
  LayoutLeaguesLeagueIdRoute: typeof LayoutLeaguesLeagueIdRouteWithChildren
}

const LayoutLeaguesRouteChildren: LayoutLeaguesRouteChildren = {
  LayoutLeaguesLeagueIdRoute: LayoutLeaguesLeagueIdRouteWithChildren,
}

const LayoutLeaguesRouteWithChildren = LayoutLeaguesRoute._addFileChildren(
  LayoutLeaguesRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutLeaguesRoute: typeof LayoutLeaguesRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutLeaguesRoute: LayoutLeaguesRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
